version: 2
jobs:
  build:
    docker:
      - image: python:3.5
    working_directory: /${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}

    steps:
      - checkout
      - setup_remote_docker

      - run:
          command: |
            ls

      - restore_cache:
          key: deps-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps-{{ checksum "requirements.txt" }}
          paths:
            - "venv"

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python manage.py test
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/
