version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5
    working_directory: ~/{{ CIRCLE_PROJECT_REPONAME }}

    steps:
      - checkout
      - setup_remote_docker

      - run: echo $PWD
      - run: ls -lah

      - restore_cache:
          key: deps-v2-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            echo $PWD
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps-v2-{{ checksum "requirements.txt" }}
          paths:
            - "venv"

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python manage.py test
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/

      - restore_cache:
          key: docker-v2
          paths:
            - ~/cache/docker-cache.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i ~/cache/docker-cache.tar | true
      - deploy:
          name:  Build docker image, and push to docker hub; deploy to cluster.
          command:     |
            export DOCKER_IMAGE="mgxyasserrabee/python-circleci-docker-k8s"
            export SERVICE_NAME="python-circleci-docker-k8s"

            set -v
            # Get version info.
            test -v CIRCLE_TAG && VERSION=$CIRCLE_TAG || VERSION=$CIRCLE_BRANCH
            export IMAGE_TAG=$VERSION"_sha-"$CIRCLE_SHA1

            # Build
            docker build --rm=false -t "$DOCKER_IMAGE:$IMAGE_TAG" .
            docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASS"
            docker push "$DOCKER_IMAGE:$IMAGE_TAG"
            docker history -q $DOCKER_IMAGE | grep missing -v

      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p ~/cache
            docker save -o ~/cache/docker-cache.tar $DOCKER_IMAGE
      - save_cache:
          key: docker-v2-{{ epoch }}
          paths:
            - ~/cache/docker-cache.tar
